/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SpellsRouteImport } from './routes/spells'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as PotionsRouteImport } from './routes/potions'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrimoireIndexRouteImport } from './routes/grimoire/index'
import { Route as AdminEditorIndexRouteImport } from './routes/admin/editor/index'
import { Route as AdminEditorPageIdRouteImport } from './routes/admin/editor/$pageId'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SpellsRoute = SpellsRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const PotionsRoute = PotionsRouteImport.update({
  id: '/potions',
  path: '/potions',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrimoireIndexRoute = GrimoireIndexRouteImport.update({
  id: '/grimoire/',
  path: '/grimoire/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorIndexRoute = AdminEditorIndexRouteImport.update({
  id: '/admin/editor/',
  path: '/admin/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorPageIdRoute = AdminEditorPageIdRouteImport.update({
  id: '/admin/editor/$pageId',
  path: '/admin/editor/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/laboratory': typeof LaboratoryRoute
  '/potions': typeof PotionsRoute
  '/quests': typeof QuestsRoute
  '/spells': typeof SpellsRoute
  '/trash': typeof TrashRoute
  '/grimoire/': typeof GrimoireIndexRoute
  '/admin/editor/$pageId': typeof AdminEditorPageIdRoute
  '/admin/editor/': typeof AdminEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/laboratory': typeof LaboratoryRoute
  '/potions': typeof PotionsRoute
  '/quests': typeof QuestsRoute
  '/spells': typeof SpellsRoute
  '/trash': typeof TrashRoute
  '/grimoire': typeof GrimoireIndexRoute
  '/admin/editor/$pageId': typeof AdminEditorPageIdRoute
  '/admin/editor': typeof AdminEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/laboratory': typeof LaboratoryRoute
  '/potions': typeof PotionsRoute
  '/quests': typeof QuestsRoute
  '/spells': typeof SpellsRoute
  '/trash': typeof TrashRoute
  '/grimoire/': typeof GrimoireIndexRoute
  '/admin/editor/$pageId': typeof AdminEditorPageIdRoute
  '/admin/editor/': typeof AdminEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/laboratory'
    | '/potions'
    | '/quests'
    | '/spells'
    | '/trash'
    | '/grimoire/'
    | '/admin/editor/$pageId'
    | '/admin/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/laboratory'
    | '/potions'
    | '/quests'
    | '/spells'
    | '/trash'
    | '/grimoire'
    | '/admin/editor/$pageId'
    | '/admin/editor'
  id:
    | '__root__'
    | '/'
    | '/laboratory'
    | '/potions'
    | '/quests'
    | '/spells'
    | '/trash'
    | '/grimoire/'
    | '/admin/editor/$pageId'
    | '/admin/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaboratoryRoute: typeof LaboratoryRoute
  PotionsRoute: typeof PotionsRoute
  QuestsRoute: typeof QuestsRoute
  SpellsRoute: typeof SpellsRoute
  TrashRoute: typeof TrashRoute
  GrimoireIndexRoute: typeof GrimoireIndexRoute
  AdminEditorPageIdRoute: typeof AdminEditorPageIdRoute
  AdminEditorIndexRoute: typeof AdminEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spells': {
      id: '/spells'
      path: '/spells'
      fullPath: '/spells'
      preLoaderRoute: typeof SpellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potions': {
      id: '/potions'
      path: '/potions'
      fullPath: '/potions'
      preLoaderRoute: typeof PotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grimoire/': {
      id: '/grimoire/'
      path: '/grimoire'
      fullPath: '/grimoire/'
      preLoaderRoute: typeof GrimoireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/': {
      id: '/admin/editor/'
      path: '/admin/editor'
      fullPath: '/admin/editor/'
      preLoaderRoute: typeof AdminEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/$pageId': {
      id: '/admin/editor/$pageId'
      path: '/admin/editor/$pageId'
      fullPath: '/admin/editor/$pageId'
      preLoaderRoute: typeof AdminEditorPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaboratoryRoute: LaboratoryRoute,
  PotionsRoute: PotionsRoute,
  QuestsRoute: QuestsRoute,
  SpellsRoute: SpellsRoute,
  TrashRoute: TrashRoute,
  GrimoireIndexRoute: GrimoireIndexRoute,
  AdminEditorPageIdRoute: AdminEditorPageIdRoute,
  AdminEditorIndexRoute: AdminEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
